#!/usr/bin/env bash
# shellcheck disable=SC2086
# script that will display information about subdomains.

get_subdomain_info() {
  # subdomains to query - array
  subdomains=("www" "lb-01" "web-01" "web-02")

  # the second argument to the Bash script is empty or not.
  if [ -z "$2" ]; then
    # user didn't provide any second argument, and the script will display information for all subdomains.
    for subdomain in "${subdomains[@]}"; do
      dig "$subdomain.$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{split($0, SUBDOMAIN, "."); print "The subdomain "SUBDOMAIN[1] " is a " $4 " record and points to " $5}'
    done
  else
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{split($0, SUBDOMAIN, "."); print "The subdomain " SUBDOMAIN[1] " is a " $4 " record and points to " $5}'
  fi
}

get_subdomain_info "$1" "$2"
