#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt-get -y  update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
# Configure nginx
echo "server {
        listen 80;
        location / {
                echo 'Hello World!';
        }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
