#!/usr/bin/env bash
# Install nginx on your web-01

# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/# listen 80/listen 80/' /etc/nginx/sites-available/default

# Configure Nginx to return "Hello World!" at root /
sudo sh -c "echo 'server {
    listen 80;
    location / {
        echo \"Hello World!\";
    }
}' > /etc/nginx/sites-available/hello-world"

# Enable the new Nginx site and disable the default site
sudo ln -s /etc/nginx/sites-available/hello-world /etc/nginx/sites-enabled/
sudo rm /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
