#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

# Update and upgrade the Ubuntu machine
sudo apt-get -y update
sudo apt-get -y upgrade

# Install Nginx web server
sudo apt-get -y install nginx

# Start Nginx
sudo service nginx start

# Create a custom 404 error page with the required string
echo "Ceci n'est pas une page." | sudo tee /var/www/html/404.html

# Edit the default Nginx configuration file to set the custom 404 error page
error_string="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "20i $error_string" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

# Reload
sudo service nginx reload
