#!/usr/bin/env bash
#  transfers a file from our client to a server using scp
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

PATH_FILE=$1
IP_SERVER=$2
USERNAME=$3
SSH_KEY=$4

scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$PATH_FILE" "$USERNAME@$IP_SERVER:~/"
