#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy=2.6.\*
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "frontend http
        bind *:80
        mode http
        default_backend web-backend
    backend web-backend
        balance roundrobin
        server 123136-web-01 35.174.209.69
        server 123136-web-02 18.208.120.192" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

service haproxy restart
