#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely. 
# I am invincible!!! when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
n=1
while [ $n -le 5 ]
do
	echo "To infinity and beyond"
	sleep 2
done
