#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# Initialize the counter
n=1
#Iterate the loop for 10 times
while [ $n -le 10 ]
do
	# Increament the value of n in each iteration
	(( n++ ))
	#check the value of n
	if [ $n == 5 ]
	then
		echo "bad luck"
		continue
	elif [ $n == 9 ]
	then
		echo "good luck"
		continue
	else
		#print the value of n on each iteration
		echo "Best School"
	fi
done
