#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
# Initialize the counter
n=1
#Iterate the loop for 20 times
while [ $n -le 20 ]
do
	#print the value of n on each iteration
	echo $n
	case $n in
		4) echo  "bad luck from China";;
		9) echo  "bad luck from Japan";;
		17) echo  "bad luck from Italy";;
	esac
	# Increament the value of n in each iteration
	(( n++ ))
done
