#!/usr/bin/env bash
# This script that gives you information about the school file.
#using if/else
FILE=school
if [ -a "$FILE" ]
then
	echo "school file exists"
	if [ ! -s "${FILE}" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "school is a regular file"
	fi

else
	echo "school file does not exist"
fi
