#!/usr/bin/env bash
# configure ngix run as nginx user must listen on all active IPs on port 8080
sudo pkill apache2
chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
